### ISSUE TITLE
Icon in index.html

### ISSUE THREAD

**Issue by tienhv** [coteditor/coteditor.github.io#10]
Hi,
I found at line 150 of index.html,
```
149 <h3>Split Editor</h3>
150					<img src="img/icons/split_view.svg" alt=""/>
```
The split_view.svg depicts wrong split panel because the application cannot split editor vertically like that. It can only do splitting horizontally.
ps: This might or might not be an issue depend on perspective.

**Comment by tienhv** [comment]
Thanks for your hard work, I found that function is "Stack Editor Horizontally". Please close this one.

**Comment by 1024jp** [comment]
☕️
