### ISSUE TITLE
Is the facebook sdk really necessary?

### ISSUE THREAD

**Issue by vordenken** [coteditor/coteditor.github.io#14]
I dont know for what exactly you use it, probably analytics? 
Facebook is known for violating users privacy and is also non foss.
Shouldnt google-analytics (which itself has a lot of problems, anti-privacy etc..) be enough?
Really like your Software though.

**Comment by 1024jp** [comment]
Thank you for the feedback and sorry for my late reply.

The Facebook SDK was used only for Facebook's "like" badge placed on the bottom part of the top page.
However, since I'm also actually not a fan of Facebook, and in response to your indication, I removed it finally.
