### ISSUE TITLE
Is Google Analytics necessary?

### ISSUE THREAD

**Issue by gracjankn** [coteditor/coteditor.github.io#15]
The privacy policy states no data is ever collected, however [Blacklight](Blacklight "https://themarkup.org/blacklight?url=coteditor.com") detected Google Analytics on this site.

Why is Google Analytics used here and is it really needed?

Google Analytics is one of the major contributors to widespread surveillance on the internet because it’s present on a significant percentage of websites and apps. [ Even FOSS which should lead by example is unfortunately no exception.](https://reverseeagle.org/about/ "Even FOSS which should lead by example is unfortunately no exception.")

Preferably we could get rid of analytics all together, but if you absolutely need to collect some basic data [here’s a list of FOSS and privacy-friendly options](https://developers.reverseeagle.org/replace/google-analytics/ "here’s a list of FOSS and privacy-friendly options").

**Comment by 1024jp** [comment]
Thank you for the feedback.

> The privacy policy states no data is ever collected, however Blacklight detected Google Analytics on this site.

The privacy policy page describes only about CotEditor.app.


> Why is Google Analytics used here and is it really needed?

I originally put the Google Analytics just to check the basic tendency of visitors, such as where they come from or how many people see each pages. However, I actually do not see the analytics data in the last years, so I deleted it.

**Comment by gracjankn** [comment]
> The privacy policy page describes only about CotEditor.app.

I didn't realize that.

> However, I actually do not see the analytics data in the last years, so I deleted it.

I checked just to be sure and it's no longer detected. Thank you for this change! 👍🏻
