### ISSUE TITLE
Localize release notes for 4.2.0 to Turkish

### ISSUE THREAD

**Issue by 1024jp** [coteditor/coteditor.github.io#23]
@bitigchi Hi, I'd like to ask you if you could localize the text added after your PR #22 in the release notes for 4.2.0. The release notes for 4.2.0-beta were good. It may help users who speak Turkish. So I'd like to reuse them for the stable 4.2.0, which I plan to release several days later.

I already made a draft for [releasenotes/4.2.0.tr.html](https://github.com/coteditor/coteditor.github.io/blob/603dee870ec09cae8d4b2f5d78b0749a35f266e4/releasenotes/4.2.0.tr.html). It would be great if you localize the English text in that and make a PR.

**Comment by bitigchi** [comment]
All done!
